# dictionary with http codes

http_status_codes = {
    100: "Continue",
    101: "Switching Protocols",
    102: "Processing",
    103: "Early Hints",

    200: "OK",
    201: "Created",
    202: "Accepted",
    203: "Non-authoritative Information",
    204: "No Content",
    205: "Reset Content",
    206: "Partial Content",
    207: "Multi Status",
    208: "Already Reported",
    226: "IM Used",

    300: "Multiple Choices",
    301: "Moved Permanently",
    302: "Found",
    303: "See other",
    305: "Use Proxy",
    307: "Temporary Redirect",
    308: "Permanent Redirect",

    400: "Bad Request",
    401: "Unauthorized",
    402: "Payment Required",
    403: "Forbidden",
    404: "Not found",
    405: "Method not allowed",
    406: "Not acceptable",
    407: "Proxy Authentication Required",
    408: "Request Timeout",
    409: "Conflict",
    410: "Gone",
    411: "Length Required",
    412: "Precondition Failed",
    413: "Payload Too Large",
    414: "Request-URI Too Long",
    415: "Unsupported Media Type",
    416: "Requested Range Not Satisfiable",
    417: "Expectation Failed",
    418: "I'm a teapot",
    421: "Misdirected Request",
    422: "Unprocessable Entity",
    423: "Locked",
    424: "Failed Dependency",
    426: "Upgrade Required",
    428: "Precondition Required",
    429: "Too many requests",
    431: "Request Header Fields Too Large",
    444: "Connection closed without response",
    451: "Unavailable For Legal Reasons",
    499: "Client Closed Request",

    500: "Internal Server Error",
    501: "Not implemented",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
    505: "HTTP Version Not Supported",
    506: "Variant Also Negotiates",
    507: "Insufficient Storage",
    508: "Loop Detected",
    510: "Not extended",
    511: "Network Authentication Required",
    599: "Network Connection Timeout Error"
}

# csv file name with actual steam market name for case price request
market_case_name = {
    "bravo_case.csv": "Operation Bravo Case",
    "breakout_case.csv": "Operation Breakout Case",
    "chroma_case": "Chroma Case",
    "chroma_2_case.csv": "Chroma 2 Case",
    "chroma_3_case.csv": "Chroma 3 Case",
    "cs20_case.csv": "CS20 Case",
    "esports_2013_case.csv": "eSports 2013 Case",
    "esports_2013_winter_case.csv": "eSports 2013 Winter Case",
    "esports_2014_summer_case.csv": "eSports 2014 Summer Case",
    "falchion_case.csv": "Falchion Case",
    "gamma_case.csv": "Gamma Case",
    "gamma_2_case.csv": "Gamma 2 Case",
    "huntsman_case.csv": "Huntsman Weapon Case",
    "prisma_case.csv": "Prisma Case",
    "prisma_2_case.csv": "Prisma 2 Case",
    "phoenix_case.csv": "Operation Phoenix Weapon Case",
    "revolver_case.csv": "Revolver Case",
    "shadow_case.csv": "Shadow Case",
    "spectrum_2_case.csv": "Spectrum 2 Case",
    "vanguard_case.csv": "Operation Vanguard Weapon Case",
    "weapon_case_2.csv": "CS:GO Weapon Case 2",
    "weapon_case_3.csv": "CS:GO Weapon Case 3",
    "weapon_case.csv": "CS:GO Weapon Case",
    "winter_offensive_case.csv": "Winter Offensive Weapon Case"
}