# this file contains lists & dicts which are imported into other files


# dictionary with http codes
http_status_codes = {
    100: "Continue",
    101: "Switching Protocols",
    102: "Processing",
    103: "Early Hints",

    200: "OK",
    201: "Created",
    202: "Accepted",
    203: "Non-authoritative Information",
    204: "No Content",
    205: "Reset Content",
    206: "Partial Content",
    207: "Multi Status",
    208: "Already Reported",
    226: "IM Used",

    300: "Multiple Choices",
    301: "Moved Permanently",
    302: "Found",
    303: "See other",
    305: "Use Proxy",
    307: "Temporary Redirect",
    308: "Permanent Redirect",

    400: "Bad Request",
    401: "Unauthorized",
    402: "Payment Required",
    403: "Forbidden",
    404: "Not found",
    405: "Method not allowed",
    406: "Not acceptable",
    407: "Proxy Authentication Required",
    408: "Request Timeout",
    409: "Conflict",
    410: "Gone",
    411: "Length Required",
    412: "Precondition Failed",
    413: "Payload Too Large",
    414: "Request-URI Too Long",
    415: "Unsupported Media Type",
    416: "Requested Range Not Satisfiable",
    417: "Expectation Failed",
    418: "I'm a teapot",
    421: "Misdirected Request",
    422: "Unprocessable Entity",
    423: "Locked",
    424: "Failed Dependency",
    426: "Upgrade Required",
    428: "Precondition Required",
    429: "Too many requests",
    431: "Request Header Fields Too Large",
    444: "Connection closed without response",
    451: "Unavailable For Legal Reasons",
    499: "Client Closed Request",

    500: "Internal Server Error",
    501: "Not implemented",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
    505: "HTTP Version Not Supported",
    506: "Variant Also Negotiates",
    507: "Insufficient Storage",
    508: "Loop Detected",
    510: "Not extended",
    511: "Network Authentication Required",
    599: "Network Connection Timeout Error"
}

# csv file name with actual steam market name for case price request
market_case_name = {
    "bravo_case.csv": "Operation Bravo Case",
    "breakout_case.csv": "Operation Breakout Weapon Case",
    "chroma_case.csv": "Chroma Case",
    "chroma_2_case.csv": "Chroma 2 Case",
    "chroma_3_case.csv": "Chroma 3 Case",
    "cs20_case.csv": "CS20 Case",
    "esports_2013_case.csv": "eSports 2013 Case",
    "esports_2013_winter_case.csv": "eSports 2013 Winter Case",
    "esports_2014_summer_case.csv": "eSports 2014 Summer Case",
    "falchion_case.csv": "Falchion Case",
    "gamma_case.csv": "Gamma Case",
    "gamma_2_case.csv": "Gamma 2 Case",
    "huntsman_case.csv": "Huntsman Weapon Case",
    "prisma_case.csv": "Prisma Case",
    "prisma_2_case.csv": "Prisma 2 Case",
    "phoenix_case.csv": "Operation Phoenix Weapon Case",
    "revolver_case.csv": "Revolver Case",
    "shadow_case.csv": "Shadow Case",
    "spectrum_case": "Spectrum Case",
    "spectrum_2_case.csv": "Spectrum 2 Case",
    "vanguard_case.csv": "Operation Vanguard Weapon Case",
    "weapon_case.csv": "CS:GO Weapon Case",
    "weapon_case_2.csv": "CS:GO Weapon Case 2",
    "weapon_case_3.csv": "CS:GO Weapon Case 3",
    "winter_offensive_case.csv": "Winter Offensive Weapon Case",
    "wildfire_case.csv": "Operation Wildfire Case",
}

case_name_into_csv = {
    "operation bravo case": "bravo_case.csv",
    "bravo case": "bravo_case.csv",
    "operation breakout case": "breakout_case.csv",
    "operation breakout weapon case": "breakout_case.csv",
    "breakout case": "breakout_case.csv",
    "breakout": "breakout_case.csv",
    "chroma case": "chroma_case.csv",
    "chroma": "chroma_case.csv",
    "chroma 2 case": "chroma_2_case.csv",
    "chroma 2": "chroma_2_case.csv",
    "chroma 3 case": "chroma_3_case.csv",
    "chroma 3": "chroma_3_case.csv",
    "cs20 case": "cs20_case.csv",
    "cs20": "cs20_case.csv",
    "cs 20": "cs20_case.csv",
    "esports 2013 case": "esports_2013_case.csv",
    "esports 2013": "esports_2013_case.csv",
    "esports 2013 winter case": "esports_2013_winter_case.csv",
    "esports 2013 winter": "esports_2013_winter_case.csv",
    "esports 2014 summer sase": "esports_2014_summer_case.csv",
    "esports 2014": "esports_2014_summer_case.csv",
    "esports 2014 summer": "esports_2014_summer_case.csv",
    "falchion case": "falchion_case.csv",
    "falchion": "falchion_case.csv",
    "gamma case": "gamma_case.csv",
    "gamma": "gamma_case.csv",
    "gamma 2 case": "gamma_2_case.csv",
    "gamma 2": "gamma_2_case.csv",
    "huntsman weapon case": "huntsman_case.csv",
    "huntsman case": "huntsman_case.csv",
    "huntsman": "huntsman_case.csv",
    "prisma case": "prisma_case.csv",
    "prisma": "prisma_case.csv",
    "prisma 2 case": "prisma_2_case.csv",
    "prisma 2": "prisma_2_case.csv",
    "operation phoenix weapon case": "phoenix_case.csv",
    "operation phoenix": "phoenix_case.csv",
    "operation phoenix case": "phoenix_case.csv",
    "revolver case": "revolver_case.csv",
    "revolver": "revolver_case.csv",
    "shadow case": "shadow_case.csv",
    "shadow": "shadow_case.csv",
    "spectrum case": "spectrum_case.csv",
    "spectrum": "specturm_case.csv",
    "spectrum 1": "spectrum_case.csv",
    "spectrum 2 case": "spectrum_2_case.csv",
    "spectrum 2": "spectrum_2_case.csv",
    "operation vanguard weapon case": "vanguard_case.csv",
    "operation vanguard case": "vanguard_case.csv",
    "operation vanguard": "vanguard_case.csv",
    "cs:go weapon case": "weapon_case.csv",
    "cs go weapon case": "weapon_case.csv",
    "cs weapon case": "weapon_case.csv",
    "cs:go weapon case 2": "weapon_case_2.csv",
    "cs go weapon case 2": "weapon_case_2.csv",
    "cs:go weapon case 3": "weapon_case_3.csv",
    "cs go weapon case 3": "weapon_case_3.csv",
    "winter offensive weapon case": "winter_offensive_case.csv",
    "winter offensive case": "winter_offensive_case.csv",
    "winter offensive": "winter_offensive_case.csv",
    "operation wild fire case": "wildfire_case.csv",
    "operation wild fire": "wildfire_case.csv"
}
