# this file contains long dictionaries, which are imported into main & functions

# stores the amount of drops for each item quality
drop_amount_by_quality = {
    "blue": 0,
    "purple": 0,
    "pink": 0,
    "red": 0,
    "yellow": 0,

    "stat_blue": 0,
    "stat_purple": 0,
    "stat_pink": 0,
    "stat_red": 0,
    "stat_yellow": 0
    }

# dictionary with http codes
http_status_codes = {
    100: "Continue",
    101: "Switching Protocols",
    102: "Processing",
    103: "Early Hints",

    200: "OK",
    201: "Created",
    202: "Accepted",
    203: "Non-authoritative Information",
    204: "No Content",
    205: "Reset Content",
    206: "Partial Content",
    207: "Multi Status",
    208: "Already Reported",
    226: "IM Used",

    300: "Multiple Choices",
    301: "Moved Permanently",
    302: "Found",
    303: "See other",
    305: "Use Proxy",
    307: "Temporary Redirect",
    308: "Permanent Redirect",

    400: "Bad Request",
    401: "Unauthorized",
    402: "Payment Required",
    403: "Forbidden",
    404: "Not found",
    405: "Method not allowed",
    406: "Not acceptable",
    407: "Proxy Authentication Required",
    408: "Request Timeout",
    409: "Conflict",
    410: "Gone",
    411: "Length Required",
    412: "Precondition Failed",
    413: "Payload Too Large",
    414: "Request-URI Too Long",
    415: "Unsupported Media Type",
    416: "Requested Range Not Satisfiable",
    417: "Expectation Failed",
    418: "I'm a teapot",
    421: "Misdirected Request",
    422: "Unprocessable Entity",
    423: "Locked",
    424: "Failed Dependency",
    426: "Upgrade Required",
    428: "Precondition Required",
    429: "Too many requests",
    431: "Request Header Fields Too Large",
    444: "Connection closed without response",
    451: "Unavailable For Legal Reasons",
    499: "Client Closed Request",

    500: "Internal Server Error",
    501: "Not implemented",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
    505: "HTTP Version Not Supported",
    506: "Variant Also Negotiates",
    507: "Insufficient Storage",
    508: "Loop Detected",
    510: "Not extended",
    511: "Network Authentication Required",
    599: "Network Connection Timeout Error"
}

# csv file name with actual steam market name for case price request
market_case_name = {
    "bravo_case.csv": "Operation Bravo Case",
    "breakout_case.csv": "Operation Breakout Weapon Case",
    "chroma_case.csv": "Chroma Case",
    "chroma_2_case.csv": "Chroma 2 Case",
    "chroma_3_case.csv": "Chroma 3 Case",
    "cs20_case.csv": "CS20 Case",
    "esports_2013_case.csv": "eSports 2013 Case",
    "esports_2013_winter_case.csv": "eSports 2013 Winter Case",
    "esports_2014_summer_case.csv": "eSports 2014 Summer Case",
    "falchion_case.csv": "Falchion Case",
    "gamma_case.csv": "Gamma Case",
    "gamma_2_case.csv": "Gamma 2 Case",
    "huntsman_case.csv": "Huntsman Weapon Case",
    "prisma_case.csv": "Prisma Case",
    "prisma_2_case.csv": "Prisma 2 Case",
    "phoenix_case.csv": "Operation Phoenix Weapon Case",
    "revolver_case.csv": "Revolver Case",
    "shadow_case.csv": "Shadow Case",
    "spectrum_case": "Spectrum Case",
    "spectrum_2_case.csv": "Spectrum 2 Case",
    "vanguard_case.csv": "Operation Vanguard Weapon Case",
    "weapon_case.csv": "CS:GO Weapon Case",
    "weapon_case_2.csv": "CS:GO Weapon Case 2",
    "weapon_case_3.csv": "CS:GO Weapon Case 3",
    "winter_offensive_case.csv": "Winter Offensive Weapon Case",
    "wildfire_case.csv": "Operation Wildfire Case",
}

# todo: all keys must be all lowercase!
case_name_into_csv = {
    "operation bravo case": "bravo_case.csv",
    "bravo case": "bravo_case.csv",
    "operation breakout case": "breakout_case.csv",
    "operation breakout weapon case": "breakout_case.csv",
    "breakout case": "breakout_case.csv",
    "breakout": "breakout_case.csv",
    "Chroma Case": "chroma_case.csv",
    "Chroma": "chroma_case.csv",
    "Chroma 2 Case": "chroma_2_case.csv",
    "Chroma 2": "chroma_2_case.csv",
    "Chroma 3 Case": "chroma_3_case.csv",
    "Chroma 3": "chroma_3_case.csv",
    "CS20 Case": "cs20_case.csv",
    "CS20": "cs20_case.csv",
    "CS 20": "cs20_case.csv",
    "eSports 2013 Case": "esports_2013_case.csv",
    "eSports 2013": "esports_2013_case.csv",
    "eSports 2013 Winter Case": "esports_2013_winter_case.csv",
    "eSports 2013 Winter": "esports_2013_winter_case.csv",
    "eSports 2014 Summer Case": "esports_2014_summer_case.csv",
    "eSports 2014": "esports_2014_summer_case.csv",
    "eSports 2014 Summer": "esports_2014_summer_case.csv",
    "Falchion Case": "falchion_case.csv",
    "Falchion": "falchion_case.csv",
    "Gamma Case": "gamma_case.csv",
    "gamma": "gamma_case.csv",
    "Gamma 2 Case": "gamma_2_case.csv",
    "Gamma 2": "gamma_2_case.csv",
    "Huntsman Weapon Case": "huntsman_case.csv",
    "Huntsman Case": "huntsman_case.csv",
    "Huntsman": "huntsman_case.csv",
    "Prisma Case": "prisma_case.csv",
    "Prisma": "prisma_case.csv",
    "Prisma 2 Case": "prisma_2_case.csv",
    "Prisma 2": "prisma_2_case.csv",
    "Operation Phoenix Weapon Case": "phoenix_case.csv",
    "Operation Phoenix": "phoenix_case.csv",
    "Operation Phoenix Case": "phoenix_case.csv",
    "Revolver Case": "revolver_case.csv",
    "Revolver": "revolver_case.csv",
    "Shadow Case": "shadow_case.csv",
    "Shadow": "shadow_case.csv",
    "Spectrum Case": "spectrum_case.csv",
    "Spectrum": "specturm_case.csv",
    "Spectrum 1": "spectrum_case.csv",
    "Spectrum 2 Case": "spectrum_2_case.csv",
    "Spectrum 2": "spectrum_2_case.csv",
    "Operation Vanguard Weapon Case": "vanguard_case.csv",
    "Operation Vanguard Case": "vanguard_case.csv",
    "Operation Vanguard": "vanguard_case.csv",
    "CS:GO Weapon Case": "weapon_case.csv",
    "CS GO Weapon Case": "weapon_case.csv",
    "CS Weapon Case": "weapon_case.csv",
    "CS:GO Weapon Case 2": "weapon_case_2.csv",
    "CS GO Weapon Case 2": "weapon_case_2.csv",
    "CS:GO Weapon Case 3": "weapon_case_3.csv",
    "CS GO Weapon Case 3": "weapon_case_3.csv",
    "Winter Offensive Weapon Case": "winter_offensive_case.csv",
    "Winter Offensive Case": "winter_offensive_case.csv",
    "Winter Offensive": "winter_offensive_case.csv",
    "Operation Wild Fire Case": "wildfire_case.csv",
    "Operation Wild Fire": "wildfire_case.csv"
}
